// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRFXm7TyHPqrJ-xBQ7fYVvNJAM5xvg5g',
    appId: '1:450242976413:web:b419b7a6da8b4416e21274',
    messagingSenderId: '450242976413',
    projectId: 'authentication-1fbe4',
    authDomain: 'authentication-1fbe4.firebaseapp.com',
    storageBucket: 'authentication-1fbe4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9k4-dJCIZTBilgYe2FTqDXFuRTTy0go',
    appId: '1:450242976413:android:81e2b6620fad716ee21274',
    messagingSenderId: '450242976413',
    projectId: 'authentication-1fbe4',
    storageBucket: 'authentication-1fbe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8xjKhozPOhgAqmsY8QK3mLjdADN0sgc',
    appId: '1:450242976413:ios:9c102ddace1c3378e21274',
    messagingSenderId: '450242976413',
    projectId: 'authentication-1fbe4',
    storageBucket: 'authentication-1fbe4.appspot.com',
    iosBundleId: 'com.example.measureAndMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8xjKhozPOhgAqmsY8QK3mLjdADN0sgc',
    appId: '1:450242976413:ios:00cf77e34d6b38d0e21274',
    messagingSenderId: '450242976413',
    projectId: 'authentication-1fbe4',
    storageBucket: 'authentication-1fbe4.appspot.com',
    iosBundleId: 'com.example.measureAndMed.RunnerTests',
  );
}
